/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.49
 * Generated at: 2020-09-16 02:42:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/WEB-INF/views/include/footer.jsp", Long.valueOf(1599785117496L));
    _jspx_dependants.put("/WEB-INF/views/include/nav.jsp", Long.valueOf(1600142923632L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1599747949337L));
    _jspx_dependants.put("/WEB-INF/views/include/aside.jsp", Long.valueOf(1599990100484L));
    _jspx_dependants.put("/WEB-INF/views/include/header.jsp", Long.valueOf(1599789170724L));
    _jspx_dependants.put("jar:file:/C:/Users/82103/Documents/shopping/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/shop/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/home.css\" />\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div id=\"root\">\n");
      out.write("\t<header id=\"header\">\n");
      out.write("\t\t<div id=\"header_box\">\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<h1 class=\"title\">\r\n");
      out.write("\t<a href=\"/\">SHOP</a>\r\n");
      out.write("</h1>\r\n");
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\t</header>\n");
      out.write("\t\n");
      out.write("\t<nav id=\"nav\">\n");
      out.write("\t\t<div id=\"nav_box\">\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<ul>\r\n");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</ul>");
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\t</nav>\n");
      out.write("\t\n");
      out.write("\t<section id=\"container\">\n");
      out.write("\t\t<aside id=\"aside\">\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<h3>카테고리</h3>\r\n");
      out.write("<ul>\r\n");
      out.write("\t<li><a href=\"/shop/list?c=100&l=1\">무기</a>\r\n");
      out.write("\t\t<ul class=\"low\">\r\n");
      out.write("\t\t\t<li><a href=\"/shop/list?c=101&l=2\">아케인셰이드</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"/shop/list?c=102&l=2\">앱솔랩스</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"/shop/list?c=103&l=2\">파프니르</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"/shop/list?c=104&l=2\">펜살리르</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"/shop/list?c=105&l=2\">무스펠</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"/shop/list?c=106&l=2\">네크로</a></li>\r\n");
      out.write("\t\t</ul>\t\r\n");
      out.write("\t</li>\r\n");
      out.write("\t<li><a href=\"/shop/list?c=200&l=1\">방어구</a>\r\n");
      out.write("\t\t<ul class=\"low\">\r\n");
      out.write("\t\t\t<li><a href=\"/shop/list?c=201&l=2\">아케인셰이드</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"/shop/list?c=202&l=2\">앱솔랩스</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"/shop/list?c=203&l=2\">파프니르</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"/shop/list?c=204&l=2\">펜살리르</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"/shop/list?c=205&l=2\">무스펠</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"/shop/list?c=206&l=2\">네크로</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</li>\r\n");
      out.write("\t<li><a href=\"/shop/list?c=300&l=1\">소비</a>\r\n");
      out.write("\t\t<ul class=\"low\">\r\n");
      out.write("\t\t\t<li><a href=\"/shop/list?c=301&l=2\">회복 아이템</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"/shop/list?c=302&l=2\">연금술 아이템</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"/shop/list?c=303&l=2\">주문서</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"/shop/list?c=304&l=2\">스킬북</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"/shop/list?c=305&l=2\">기타</a></li>\r\n");
      out.write("\t\t</ul>\t\r\n");
      out.write("\t</li>\r\n");
      out.write("\t<li><a href=\"/shop/list?c=400&l=1\">캐시</a>\r\n");
      out.write("\t\t<ul class=\"low\">\r\n");
      out.write("\t\t\t<li><a href=\"/shop/list?c=401&l=2\">강화</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"/shop/list?c=402&l=2\">게임</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"/shop/list?c=403&l=2\">코디</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"/shop/list?c=404&l=2\">뷰티</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"/shop/list?c=405&l=2\">펫</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"/shop/list?c=406&l=2\">기타</a></li>\r\n");
      out.write("\t\t</ul>\t\r\n");
      out.write("\t\r\n");
      out.write("\t</li>\r\n");
      out.write("\t<li><a href=\"/shop/list?c=500&l=1\">기타</a>\r\n");
      out.write("\t\t<ul class=\"low\">\r\n");
      out.write("\t\t\t<li><a href=\"/shop/list?c=501&l=2\">의자</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"/shop/list?c=502&l=2\">전문기술</a></li>\r\n");
      out.write("\t\t</ul>\t\r\n");
      out.write("\t</li>\r\n");
      out.write("</ul>\r\n");
      out.write("\n");
      out.write("\t\t</aside>\n");
      out.write("\t\t<div id=\"container_box\">\n");
      out.write("\t\t\t본문영역\n");
      out.write("\t\t</div>\n");
      out.write("\t</section>\n");
      out.write("\t\n");
      out.write("\t<footer id=\"footer\">\n");
      out.write("\t\t<div id=\"footer_box\">\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<ul>\r\n");
      out.write("\t<li>사이트 소개</li>\r\n");
      out.write("\t<li>이용약관</li>\r\n");
      out.write("\t<li>SHOP</li>\r\n");
      out.write("</ul>");
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\t</footer>\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/include/nav.jsp(4,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member == null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t<li>\r\n");
          out.write("\t\t<a href=\"/member/signIn\">로그인</a>\r\n");
          out.write("\t</li>\r\n");
          out.write("\t<li>\r\n");
          out.write("\t\t<a href=\"/member/signUp\">회원가입</a>\r\n");
          out.write("\t</li>\r\n");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/include/nav.jsp(12,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write('\r');
          out.write('\n');
          out.write('	');
          if (_jspx_meth_c_005fif_005f2(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t<li>\r\n");
          out.write("\t\t");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.userName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("님 환영합니다.\r\n");
          out.write("\t</li>\r\n");
          out.write("\t<li>\r\n");
          out.write("\t\t<a href=\"/shop/cartList\">카트 리스트</a>\r\n");
          out.write("\t</li>\r\n");
          out.write("\t\t<li>\r\n");
          out.write("\t\t<a href=\"/shop/orderList\">주문 리스트</a>\r\n");
          out.write("\t</li>\r\n");
          out.write("\t<li>\r\n");
          out.write("\t\t<a href=\"/member/signOut\">로그아웃</a>\r\n");
          out.write("\t</li>\r\n");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/views/include/nav.jsp(13,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.verify == 9}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t<li>\r\n");
          out.write("\t\t<a href=\"/admin/index\">관리자 화면</a>\r\n");
          out.write("\t</li>\r\n");
          out.write("\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }
}
